### ISSUE TITLE
Overlays contain transparent / translucent pixels outside the desired area

### ISSUE THREAD

**Issue by toniosj** [thebezelproject/bezelproject-Atari2600#1]
Some overlays contain transparent / translucent pixels outside the desired area.

Here the list:

Adventure (USA).png
Base Attack (USA).png
Cubicolor (USA) (Proto).png
Human Cannonball - Cannon Man (USA).png
Jr. Pac-Man (USA).png
Looping (USA) (Proto).png
Mines of Minos (USA).png
Miniature Golf - Arcade Golf (USA).png
Mission 3,000 A.D. (USA).png
Mission Survive (Europe).png
Pete Rose Baseball (USA).png
Phaser Patrol (USA).png
Pick 'n' Pile (Europe).png
Polaris (USA).png
RealSports Tennis (USA).png
Revenge of the Beefsteak Tomatoes (USA).png
Tooth Protectors (USA).png
Unknown 20th Century Fox Game (USA) (Proto).png

Here you can see the specific areas that have pixels outside the desired area.

https://drive.google.com/file/d/11yWoM5JFL2wUWdUzm2Ho9svykuQRi8pW/view?usp=sharing

**Comment by thebezelproject** [comment]
Files have been updated.
