### ISSUE TITLE
Wrong .cfg location for Stella 2014

### ISSUE THREAD

**Issue by Drab-Crab** [thebezelproject/bezelproject-Atari2600#2]
The bezel installation script for Stella 2014 (atari 2600) drops the .cfg in the wrong location. The script downloads and saves them to /opt/retropie/configs/all/retroarch/config/Stella2014 however, the Stella 2014 emulator looks in /opt/retropie/configs/all/retroarch/config/Stella 2014 for the .cfg files.

I was only getting the default system overlay when starting games. I moved all the files from /opt/retropie/configs/all/retroarch/config/Stella2014 to /opt/retropie/configs/all/retroarch/config/Stella 2014 and then all the individual bezels starting loading for games.

**Comment by thebezelproject** [comment]
Thanks for the info. The repo has been updated.
