### ISSUE TITLE
Transparent pixels

### ISSUE THREAD

**Issue by toniosj** [thebezelproject/bezelproject-Atari2600#3]
I've found some transparent pixles.

Barnstorming (USA).png
Glib - Video Word Game (USA).png
Motocross Racer (USA).png
Planet of the Apes (USA) (Proto).png
Quadrun (USA).png
Star Raiders (USA).png
Star Voyager (USA).png
Stargate (USA).png
Tutankham (USA).png

![Barnstorming (USA)](https://user-images.githubusercontent.com/20826760/101471472-a7773200-3947-11eb-923b-83cb112017d5.png)
![Glib - Video Word Game (USA)](https://user-images.githubusercontent.com/20826760/101471479-a80fc880-3947-11eb-93ae-cd491554e97e.png)
![Motocross Racer (USA)](https://user-images.githubusercontent.com/20826760/101471483-a8a85f00-3947-11eb-91a3-051e2144e595.png)
![Planet of the Apes (USA) (Proto)](https://user-images.githubusercontent.com/20826760/101471487-a940f580-3947-11eb-9ef4-fb69e74d3662.png)
![Quadrun (USA)](https://user-images.githubusercontent.com/20826760/101471488-a9d98c00-3947-11eb-9a73-8f3bbf1be98a.png)
![Star Raiders (USA)](https://user-images.githubusercontent.com/20826760/101471489-aa722280-3947-11eb-98a7-edc37f3552a3.png)
![Star Voyager (USA)](https://user-images.githubusercontent.com/20826760/101471493-ab0ab900-3947-11eb-891b-a6b9291dc9af.png)
![Stargate (USA)](https://user-images.githubusercontent.com/20826760/101471497-aba34f80-3947-11eb-9edd-46dc28afcd5f.png)
![Tutankham (USA)](https://user-images.githubusercontent.com/20826760/101471501-acd47c80-3947-11eb-89e4-a9d8f9a47c2b.png)

**Comment by thebezelproject** [comment]
Updated.
