### ISSUE TITLE
More homebrews?

### ISSUE THREAD

**Issue by thrust26** [thebezelproject/bezelproject-Atari2600#5]
It looks like there are no homebrew bezels for anything newer than ~7 years. Are there any plans to fill the gap?

**Comment by thebezelproject** [comment]
While there are no active plans, all the project bezel packs will be revisited once all the initial systems are finished.

**Comment by thrust26** [comment]
> While there are no active plans, all the project bezel packs will be revisited once all the initial systems are finished.

Thanks for the info. But will that ever be done? 😉
